# Generated by Django 3.0.6 on 2020-06-02 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teams',
            name='teamamount',
            field=models.IntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='teams',
            name='teamsize',
            field=models.IntegerField(default=5),
        ),
    ]
